apiVersion: apps/v1
kind: Deployment
metadata:
  name: swiggy-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
      version: blue
  template:
    metadata:
      labels:
        app: swiggy
        version: blue
    spec:
      containers:
        - name: cont-1
          image: irfan7781/mytetris:v2
          ports:
            - containerPort: 3000
