apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: NodePort
  selector:
    app: swiggy
    version: blue   # <--- change to green when ready
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
